# Generated by Django 6.0.8 on 2026-08-16 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("tagline", models.CharField(blank=True, max_length=160)),
                ("description", models.TextField(blank=True)),
                ("position", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("position", "name"),
            },
        ),
        migrations.CreateModel(
            name="Opening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "alternative_names",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Other names the opening goes by.",
                    ),
                ),
                (
                    "eco_range",
                    models.CharField(
                        blank=True, help_text="e.g. C60-C99", max_length=20
                    ),
                ),
                (
                    "colour",
                    models.CharField(
                        choices=[
                            ("white", "Played by White"),
                            ("black", "Played by Black"),
                        ],
                        default="white",
                        max_length=5,
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=200)),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Two or three sentences, plain text."
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Long form theory, Markdown."
                    ),
                ),
                (
                    "moves_san",
                    models.JSONField(
                        default=list,
                        help_text="Defining moves from the start position.",
                    ),
                ),
                ("moves_uci", models.JSONField(default=list)),
                (
                    "fen",
                    models.CharField(
                        default="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
                        max_length=100,
                    ),
                ),
                ("first_played", models.CharField(blank=True, max_length=60)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="openings",
                        to="curriculum.section",
                    ),
                ),
            ],
            options={
                "ordering": ("section__position", "position", "name"),
            },
        ),
        migrations.CreateModel(
            name="Variation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100)),
                ("name", models.CharField(max_length=140)),
                ("eco", models.CharField(blank=True, max_length=10)),
                ("tagline", models.CharField(blank=True, max_length=200)),
                (
                    "idea",
                    models.TextField(
                        blank=True,
                        help_text="What both sides are actually trying to do.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Long form theory, Markdown."
                    ),
                ),
                (
                    "moves_san",
                    models.JSONField(
                        default=list,
                        help_text="Full move list from the start position.",
                    ),
                ),
                ("moves_uci", models.JSONField(default=list)),
                (
                    "fen",
                    models.CharField(
                        default="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
                        max_length=100,
                    ),
                ),
                ("is_main_line", models.BooleanField(default=False)),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="1 easy .. 5 hard, drives the recommended order.",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "opening",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="curriculum.opening",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="curriculum.variation",
                    ),
                ),
            ],
            options={
                "ordering": ("opening__position", "position", "name"),
            },
        ),
        migrations.CreateModel(
            name="TheoryBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("idea", "Key idea"),
                            ("plan", "Typical plan"),
                            ("structure", "Pawn structure"),
                            ("trap", "Trap to know"),
                            ("warning", "Common mistake"),
                            ("game", "Model game"),
                        ],
                        default="idea",
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("body", models.TextField(help_text="Markdown.")),
                (
                    "fen",
                    models.CharField(
                        blank=True, help_text="Diagram, optional.", max_length=100
                    ),
                ),
                ("moves_san", models.JSONField(blank=True, default=list)),
                ("moves_uci", models.JSONField(blank=True, default=list)),
                (
                    "highlight_squares",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Squares to mark on the diagram, e.g. ['d5', 'f5'].",
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[("white", "White"), ("black", "Black")],
                        default="white",
                        max_length=5,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theory_blocks",
                        to="curriculum.variation",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="variation",
            constraint=models.UniqueConstraint(
                fields=("opening", "slug"), name="unique_variation_slug"
            ),
        ),
    ]
