# Generated by Django 6.0.8 on 2026-08-16 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Stable identifier so re-seeding updates instead of duplicating.",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("theory", "Play the theoretical move"),
                            ("tactic", "Win material or mate"),
                            ("plan", "Find the right plan"),
                            ("trap", "Punish the mistake"),
                            ("recall", "Recall the move order"),
                        ],
                        default="theory",
                        max_length=10,
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Introductory"),
                            (2, "Easy"),
                            (3, "Medium"),
                            (4, "Hard"),
                            (5, "Expert"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "prompt",
                    models.CharField(
                        help_text="What the user has to do.", max_length=240
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Shown once the attempt is finished."
                    ),
                ),
                (
                    "fen",
                    models.CharField(
                        help_text="Position the user starts from.", max_length=100
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[("white", "White"), ("black", "Black")],
                        default="white",
                        max_length=5,
                    ),
                ),
                (
                    "side_to_move",
                    models.CharField(
                        choices=[("white", "White"), ("black", "Black")],
                        default="white",
                        max_length=5,
                    ),
                ),
                (
                    "setup_moves_san",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Moves that led to the position, for context.",
                    ),
                ),
                ("solution", models.JSONField(default=list)),
                ("hint", models.CharField(blank=True, max_length=240)),
                (
                    "themes",
                    models.JSONField(
                        blank=True, default=list, help_text="e.g. ['fork', 'pin']."
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="curriculum.variation",
                    ),
                ),
            ],
            options={
                "ordering": ("variation__position", "difficulty", "position", "id"),
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("solved", "Solved"), ("failed", "Failed")],
                        max_length=6,
                    ),
                ),
                (
                    "moves_played",
                    models.JSONField(
                        default=list, help_text="UCI moves the user actually played."
                    ),
                ),
                (
                    "failed_at_ply",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Index in `solution` where the line broke.",
                        null=True,
                    ),
                ),
                ("expected_move", models.CharField(blank=True, max_length=10)),
                ("played_move", models.CharField(blank=True, max_length=10)),
                ("hints_used", models.PositiveSmallIntegerField(default=0)),
                ("gave_up", models.BooleanField(default=False)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="exercises.exercise",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ExerciseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unseen", "Not attempted"),
                            ("solved", "Solved"),
                            ("failed", "Failed"),
                        ],
                        default="unseen",
                        max_length=6,
                    ),
                ),
                ("attempts_count", models.PositiveIntegerField(default=0)),
                ("solved_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                (
                    "best_duration_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("first_solved_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("needs_review", models.BooleanField(default=False)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="exercises.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["kind", "difficulty"], name="exercises_e_kind_167f19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["is_active"], name="exercises_e_is_acti_763092_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(
                fields=["user", "-created_at"], name="exercises_a_user_id_329410_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(
                fields=["user", "exercise"], name="exercises_a_user_id_6a85ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exerciseprogress",
            index=models.Index(
                fields=["user", "status"], name="exercises_e_user_id_dfa425_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exerciseprogress",
            index=models.Index(
                fields=["user", "needs_review"], name="exercises_e_user_id_15ebf7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="exerciseprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "exercise"), name="unique_user_exercise"
            ),
        ),
        migrations.AddConstraint(
            model_name="exerciseprogress",
            constraint=models.CheckConstraint(
                condition=models.Q(("solved_count__lte", models.F("attempts_count"))),
                name="solved_not_greater_than_attempts",
            ),
        ),
    ]
